version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: my_store
      POSTGRES_USER: carapoia
      POSTGRES_PASSWORD: L@Trinid@d2006
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: cesarlch2409@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: my_store
      MYSQL_ROOT_PASSWORD: L@Trinid@d2006
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: L@Trinid@d2006
      PMA_HOST: mysql
    ports:
      - 8080:80

